# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5

    - uses: pyupio/safety-action@v1
      with:
        api-key: ${{ secrets.SAFETY_API_KEY }}

    - name: Run Pysa Action
      uses: facebook/pysa-action@1
      with:
        repo-directory: './'
        requirements-path: 'requirements.txt'
        infer-types: true
        include-default-sapp-filters: true

    - name: Build and scan image
      uses: dentsusoken/build-and-scan-image@main
      with:
        tag: sashapo12/app-after-pipeline:tester
        path: "."
